class sparkle(object):
    reset = '\033[0m'
    charcoal = '\033[30m'
    grey = '\033[90m'
    wine = '\033[31m\033[2m'
    red = '\033[31m'
    cherry = '\033[91m'
    bronze = '\033[33m\033[2m'
    gold = '\033[33m'
    yellow = '\033[93m'
    grass = '\033[92m'
    green = '\033[32m'
    forest = '\033[32m\033[2m'
    teal = '\033[36m\033[2m'
    cyan = '\033[36m'
    sky = '\033[96m'
    baby = '\033[94m'
    blue = '\033[34m'
    royal = '\033[34m\033[2m'
    magenta = '\033[35m\033[2m'
    purple = '\033[35m'
    violet = '\033[95m'
    light = '\033[37m'
    white = '\033[97m'

if __name__ == '__main__':
    print sparkle.wine + '!' + sparkle.reset + sparkle.red + '!' + sparkle.reset + sparkle.cherry + 't' + sparkle.reset + sparkle.bronze + 'w' + sparkle.reset + sparkle.gold + 'i' + sparkle.reset + sparkle.yellow + 'l' + sparkle.reset + sparkle.grass + 'i' + sparkle.reset + sparkle.green + 'g' + sparkle.reset + sparkle.forest + 'h' + sparkle.reset + sparkle.teal + 't' + sparkle.reset + sparkle.cyan + '.' + sparkle.reset + sparkle.sky + 's' + sparkle.reset + sparkle.baby + 'p' + sparkle.reset + sparkle.blue + 'a' + sparkle.reset + sparkle.royal + 'r' + sparkle.reset + sparkle.magenta + 'k' + sparkle.reset + sparkle.purple + 'l' + sparkle.reset + sparkle.violet + 'e' + sparkle.reset + sparkle.white + '!' + sparkle.reset + sparkle.light + '!' + sparkle.reset + sparkle.grey + '!' + sparkle.reset + sparkle.charcoal + '!' + sparkle.reset
